server:
  port: 8081
spring:
  application:
    name: api-person
  session:
    store-type: none
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true


#  redis:
#    host: vens.com
#    port: 6379
#    password:



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true