server:
  port: 8081
spring:
  application:
    name: api-person
  session:
    store-type: none
#  redis:
#    host: vens.com
#    port: 6379
#    password:



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true