server:
  port: 8081
spring:
  application:
    name: api-person
  session:
    store-type: none
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  mvc:
    view:
      prefix: /
      suffix: .html

profile:
  store-path: D:/img/staff/profile
  server-url: localhost:8081/profile/



eureka:
  client:
    serviceUrl:
      defaultZone: http://119.29.75.134:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000