server:
  port: 8081
  session:
    timeout: 2000
spring:
  application:
    name: api-person
#  session:
#    store-type: redis
#  redis:
#    host: vens.com
#    port: 6379
#    password:



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true