server:
  port: 8081
  session:
    timeout: 10000
spring:
  application:
    name: api-person
  session:
    store-type: redis
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
  mvc:
    view:
      prefix: /
      suffix: .html
  redis:
    host: 119.29.75.134
    port: 6379
    password: 7416kobe
#    static-path-pattern: /image/**
#  resources:
#    static-locations: file:D:/img/staff/profile

profile:
  store-path: D:/img/staff/profile
  server-url: http://localhost:8081/image/



eureka:
  client:
    serviceUrl:
      defaultZone: http://119.29.75.134:8761/eureka/
  instance:
    prefer-ip-address: true
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 10000